<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testing" nsURI="http:///hu/bme/mit/plcspec/alloygenerator/testing.ecore"
    nsPrefix="hu.bme.mit.plcspec.alloygenerator.testing">
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCoverages" upperBound="-1"
        eType="#//TestCoverage" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sutName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapter" eType="#//Adapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCoverage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCases" upperBound="-1"
        eType="#//TestCase" containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
